micronaut:
  application:
    name: fretesRest

grpc:
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    fretes:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attemps: 10